language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1
    - php: nightly

before_script:
  - composer install

script:
  - phpunit --configuration tests/phpunit.xml