language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml
  - ./vendor/bin/phpstan analyse -c tests/phpstan.neon.dist --no-progress --no-interaction --level=4 lib/

after_success:
  - bash <(curl -s https://codecov.io/bash)
